common:        
   pcd_save_en: false  
   Save_path: true
   use_cam: true
   ROOT_DIR: "/home/cxl/code/A-MY-WORK/KISS-LV/src/kiss_lv/ros/results"
   save_frame_num_beg: 1
   save_frame_num_end: 1600
   lidar_topic: "/livox/lidar"
   image_topic: "/usb_cam/image_raw"    
   child_frame: "base_link"
   odom_frame: "odom"

kiss_l:
   voxel_size: 1.0
   max_range: 100
   min_range: 0.0
   min_motion_th: 0.01
   initial_threshold: 1
   lidar_type: "LIVOX"
   Deskew: true
   Exp_key_num: 1000

kiss_v:
   line_len: 30
   line_wide: 2
   point_th: 500
   radius_size: 2
   image_height: 1080        
   image_weight: 1920   
   distCoeffs: [0.0372467, -0.0318484, -0.00147466, -0.00167111, 0] 
   # Fine extrinsic value. form camera-LiDAR calibration.
   intrisicMat:
      [1223.68, 0.000000, 1290.39,
    0.000000, 1223.95, 800.944,
    0.0, 0.0, 1.0 ] 
   extrinsicMat_RT:
         [-0.0251337,-0.999684,6.2491e-05,-0.00614339,
          0.405899,-0.0102621,-0.91386,-0.0658063,
          0.913572,-0.0229433,0.406029,0.0350411,
          0.0, 0.0, 0.0, 1.0]
